spring:
  application:
    name: inventory-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/inventorydb}
    username: ${SPRING_DATASOURCE_USERNAME:inventory_user}
    password: ${SPRING_DATASOURCE_PASSWORD:inventory_password}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
