spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/orderdb}
    username: ${SPRING_DATASOURCE_USERNAME:order_user}
    password: ${SPRING_DATASOURCE_PASSWORD:order_password}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

server:
  port: 8083

services:
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8081}
  inventory-service:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
