apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: ordermanagement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/order-management/inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: inventory-service-db
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 15
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: ordermanagement
spec:
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
