apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ordermanagement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/order-management/product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: product-service-db
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 15
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ordermanagement
spec:
  selector:
    app: product-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
