apiVersion: v1
kind: Secret
metadata:
  name: product-service-db
  namespace: ordermanagement
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://product-db.cluster-xxxxxxxx.ap-south-1.rds.amazonaws.com:5432/productdb
  SPRING_DATASOURCE_USERNAME: product_user
  SPRING_DATASOURCE_PASSWORD: replace-me
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-db
  namespace: ordermanagement
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db.cluster-xxxxxxxx.ap-south-1.rds.amazonaws.com:5432/inventorydb
  SPRING_DATASOURCE_USERNAME: inventory_user
  SPRING_DATASOURCE_PASSWORD: replace-me
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-db
  namespace: ordermanagement
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://order-db.cluster-xxxxxxxx.ap-south-1.rds.amazonaws.com:5432/orderdb
  SPRING_DATASOURCE_USERNAME: order_user
  SPRING_DATASOURCE_PASSWORD: replace-me
